### ISSUE TITLE
hi can I join legendrom team

### ISSUE THREAD

**Issue by frap129** [LegendROM-N/android_packages_apps_Settings#6]

**Comment by jhalayashraj** [comment]
Hey @frap129 I'm not sure if you're being sarcastic but I hope there are no misunderstandings between us. If some exist, please ping me on telegram and we can sort them out. Thanks.

**Comment by frap129** [comment]
Sorry, there was a short period where I was fired from Carbon by @pcamp96, was simply exploring my options.
